---

before_script:
  - ruby --version
  - gem --version
  - gem install bundler
  - bundle --version
  - bundle config set path vendor
  - bundle install --retry=3

lint:
  image: ruby:2.6
  except:
    - schedules
  script:
    - bundle exec rubocop .
  cache:
    paths:
      - vendor/ruby

todos:
  image: ruby:2.6
  only:
    refs:
      - schedules
    variables:
      - $GITLAB_TOKEN
  script:
    - bundle exec ./bin/pto-tanuki
  cache:
    paths:
      - vendor/ruby
