---
AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 1000

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 10

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/UncommunicativeMethodParamName:
  Enabled: false
